---
sidebar: sidebar 
permalink: workspaces/prepare-data-for-aide.html 
keywords: aide, workspaces, create data container, ai data engine 
summary: 创建集群后，您可以创建一个数据容器，其中包含您打算与 AI Data Engine 一起使用的数据。 
---
= 为 AI Data Engine 准备数据
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
创建集群后，建立一个数据容器，其中包含您打算与 AI Data Engine (AIDE) 一起使用的数据。此数据容器必须是 ONTAP 卷，可以是本地卷或来自运行 ONTAP 9 的对等 ONTAP 集群的卷。

您无需手动将 ONTAP 群集数据上传到 AIDE，而是需要将目标群集和 SVM 与 AIDE 群集对等，然后确定要将哪些 NFS 卷与 AIDE 元数据目录一起使用。创建数据容器后，可以创建一个工作区，并将数据容器与该工作区关联。然后，该工作区的用户可以访问其 AI 工作负载的工作区关联数据集和资源并与之交互。

.关于此任务
必须对包含要用于 AI Data Engine 的数据的每个 SVM 进行对等。仅对等集群是不够的。这确保了 AI Data Engine 可以按预期访问、载入和索引您的数据。

您应该对等 AIDE 集群中将充当 SnapMirror 目标的 SVM。

您不需要在 ONTAP 集群和 AIDE 集群之间创建 SnapMirror 关系。这些关系将在工作区创建过程中自动创建。

.开始之前
* 您需要 _storage administrator_ 权限才能对等集群和 SVM 并选择数据容器。
* 您已确定包含要用于 AI Data Engine 的数据的 ONTAP 集群和 SVM。
* 您已确认数据源卷满足以下要求：
+
** 卷处于联机状态且可访问。
** 已启用 NFS 协议。仅支持启用 NFS 的卷作为 AI Data Engine 的数据容器。不支持 SMB 和 CIFS 卷。
** 卷不是 FlexCache 卷。
** 数据源是读写卷。不支持数据保护卷。




.步骤
. https://docs.netapp.com/us-en/ontap-afx/protect-data/create-peer-relationship.html["对等每个 ONTAP 集群和 SVM"^] 包含要用于 AI Data Engine 的数据。
. link:../install-setup/cluster-setup-afx.html["选择要用于 AI Data Engine 的卷"]。
+
对于每个卷，请注意以下信息：

+
** 卷名称
** UUID
** SVM 名称和 UUID
** 集群名称和 UUID




.下一步是什么？
link:create-workspace.html["创建工作区"] 并将您创建的数据容器与工作区相关联。

.相关信息
* https://docs.netapp.com/us-en/ontap-afx/manage-data/prepare-manage-data.html#data-migration-options["数据迁移选项"^]

